#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=30G
#SBATCH --gres=gpu:1
#SBATCH --time="-1"
#SBATCH --array=0-53%10

$CUDA_VISIBLE_DEVICES
list=(
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_aae2_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_aae10_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_aae100_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae2_rd_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rd_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae100_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=linear_vae100_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rerun_rs11"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rerun_rs12"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rerun_rs13"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rerun_rs14"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rerun_rs15"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_rerun_rs16"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_mp_010_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_mp_020_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_mp_050_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_mp_080_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_mp_090_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_mp_099_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_blur5_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_blur2_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_blur1_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_blur01_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_vae10_blur05_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_deep_gan5_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_deep_gan10_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_deep_gan2_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_shallow_gan5_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_shallow_gan10_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_shallow_gan2_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_shallow_gan100_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_deep_gan100_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_aae2_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_aae10_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_deep_gan5_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_deep_gan10_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_deep_gan2_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_shallow_gan5_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_shallow_gan10_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_shallow_gan2_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_vae10_rd_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=fid_icml_vae2_rd_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan5_BRE_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan10_BRE_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan100_BRE_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan5_SN_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan10_SN_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan100_SN_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan5_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan10_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan100_GP_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan5_V_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan10_V_rerun"
"cd ~/00sync/rate_distortion && python -m rate_distortion.main --hparam_set=icml_CIFAR10_dcgan100_V_rerun"
)
echo "Starting task $SLURM_ARRAY_TASK_ID: ${list[SLURM_ARRAY_TASK_ID]}"
echo $CUDA_VISIBLE_DEVICES
eval ${list[SLURM_ARRAY_TASK_ID]}
